export const productos = [
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
  {
    sku: "7028",
    precio: 2000,
    descripcion: "Cerveza Brahma 24un. 473ml",
    categoria: "cervezas",
    marca: "Brahma",
  },
];
